### PR TITLE
oc_log-cron-converter.sh from owncloud/GCX/...

### PR DESCRIPTION
**Pull request by jnweiger**

### CODE REVIEW

**Comment by cdamken** [comment]
Could we make the first search faster? 😸

**Comment by jnweiger** [comment]
the first find searches recursvely. Bad idea. It should only seach on the toplevel folder of each user.

`find /srv/www/owncloud -type d -iname oc-logs -maxdepth 2 ....`

**Comment by cdamken** [comment]
I know, the user has to have it only in the first level
```
find /srv/www/owncloud/*/files -type d -iname oc-logs -maxdepth 2 ....
```

**Comment by Kawohl** [comment]
Awesome stuff!

**Pull request merged**
